### PR TITLE
CommunicationDeterminismChecker done!

### PR DESCRIPTION
**Pull request by eazimi**
CommunicationDeterminismChecker class doesn't use RemotePtr

### CODE REVIEW

**Comment by mquinson** [comment]
Well, I think you MUST sort your PRs out. Most of them are loaded with commits that are already integrated in master, and many commits are also shared between PRs...

I will merge this branch today because I think it contain all of your work, but you should definitely review the others. Please do read the commits that you added to each PR, and observe how intermixed things are.

**Comment by eazimi** [comment]
> Well, I think you MUST sort your PRs out. Most of them are loaded with commits that are already integrated in master, and many commits are also shared between PRs...
> 
> I will merge this branch today because I think it contain all of your work, but you should definitely review the others. Please do read the commits that you added to each PR, and observe how intermixed things are.

The PRs are accumulative, if you go for last PR, it includes all changes from previous commits. However, you can recognize latest developments by considering the dates of commits.

**Comment by eazimi** [comment]
> Well, I think you MUST sort your PRs out. Most of them are loaded with commits that are already integrated in master, and many commits are also shared between PRs...
> 
> I will merge this branch today because I think it contain all of your work, but you should definitely review the others. Please do read the commits that you added to each PR, and observe how intermixed things are.

Each new pull request definitely contains new developments. If you merge latest PR, you can ditch the others.

**Comment by eazimi** [comment]
> > Sort your PRs ... 
I guess they are sorted right now. But if you think differently, please share your hints with me.

> > read the commits that you added to each PR, and observe how intermixed things are.
Yeap, because the new branch stacked up on top of the branch that the latest pull request is issued from there. Actually I have no idea why I did like that! 
Please let me know if there is any convention for creating pull requests.

**Pull request closed without merging**
