### PR TITLE
Replay steroid example

### PR DESCRIPTION
**Pull request by mpoquet**
This branch adds an example corresponding to #129.
It is a micro Batsim program that mixes MSG and SMPI jobs.

The example should not work with current SimGrid version.
However, it may work soon with upcoming @Shurakai's SMPI improvements.

### CODE REVIEW

**Comment by mquinson** [comment]
Then, let's wait for the fix to enter before allowing the test. Thanks for your time, Mt.

**Comment by mquinson** [comment]
Hello,

this code does not even compile :-P And nope, it's not because of the recent API changes:
```
/home/travis/build/simgrid/simgrid/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual.cpp: In function ‘bool job_comparator(const Job*, const Job*)’:
/home/travis/build/simgrid/simgrid/examples/smpi/replay_multiple_manual_deploy/replay_multiple_manual.cpp:41:6: error: no previous declaration for ‘bool job_comparator(const Job*, const Job*)’ [-Werror=missing-declarations]
 bool job_comparator(const Job * j1, const Job * j2)
      ^
```

**Comment by mpoquet** [comment]
Indeed, wild psychorigid compilation warnings appeared.
Should be fixed as fea491ec2 (pushed to gforge's `replay-steroid-example` branch).

(Tested merge on old SG, not the current one).

```
git fetch gforge
git checkout replay-steroid-example
mkdir build
# nix-shell --pure -p cmake perl elfutils python3 boost valgrind
cmake .. -Denable_documentation=OFF -Denable_compile_warnings=ON
make
```

**Comment by mquinson** [comment]
Does #265 mean that we can close #176?

Thanks,

**Comment by mpoquet** [comment]
Yes.

**Pull request closed without merging**
