### PR TITLE
SMPI privatization based on dlopen

### PR DESCRIPTION
**Pull request by randomstuff**
⚠️ **Not ready for merging.**

The idea is that the SMPI user code is now compiled as a dynamic library which is dynamically loaded into the Simgrid/SMPI process (the `smpi_main` executable):
* either once, for the classical privatization options ("no", "mmap");
* or once per simulated process, for the new privatization mode ("dlopen").

Basic stuff:

* [x] Repair classic privatization mode
* [x] Fix `smpi_main` handling (`PATH`, installation, etc.)
* [x] Make it work with Fortran (`mpiff`, `mpif90`)
* [x] Don't rely on external `cp` command
* [x] Cleanup

Cross platform:

* [ ] <del>Fix SMPI on Windows</del>
* [x] Fix SMPI on MacOS X
* [x] New privatization on BSD (probably won't work because of lack of `RTLD_DEEPBIND`)

Optional optimizations :

* [ ] Deduplicate in-memory pages of the text segment using `mmap` (unless a `reflink` was used)
* [ ] `ftruncate` and punch-holes in the on-disk copies

Debugging :

* [ ] Investigate behaviour wrt debuggers (unlinking the file immediately, additional messing-up with the file)

Model-checker:

* [ ] Fix the model checker
* [ ] Support for the new privatization mode

### CODE REVIEW

**Comment by randomstuff** [comment]
Fortran fixed.

`100% tests passed, 0 tests failed out of 258` \o/

**Comment by randomstuff** [comment]
The bad news is that for it to work correctly, we need `RTLD_DEEPBIND` which is GNU-libc specific.

**Comment by mquinson** [comment]
RTLD_DEEPBIND is an ugly pimple to fix the behavior of the gnu ld. Other ld don't need it, so we're good.

From my POV, we still need to fix MC (if broken), and cleanup. Optimizations are not mandatory.

**Comment by mquinson** [comment]
I confirm that MC is broken on that branch. Conditional jump or move depends on uninitialised value(s) on the following line of mc::~Process()
```C
  if (this->unw_underlying_addr_space != unw_local_addr_space) {
```

Ouch, too hard for me, I'm affraid.

**Comment by mquinson** [comment]
Augustin told me that this branch is working on winbuntu, and SMPI never worked on Windows without that subsystem, so I think we're good on that front.

**Comment by randomstuff** [comment]
As discussed in #139, reflink won't give us page sharing the page cache works per inode on Linux.

**Comment by randomstuff** [comment]
See the [docker doc](https://docs.docker.com/engine/userguide/storagedriver/btrfs-driver/):

> **Page caching.** Btrfs does not support page cache sharing. This means that n containers accessing the same file require n copies to be cached. As a result, the btrfs driver may not be the best choice for PaaS and other high density container use cases.

**Comment by randomstuff** [comment]
See alos [this thread](http://www.spinics.net/lists/linux-btrfs/msg38790.html) with a simple test showing the lack of page cache sharing between reflinks.

**Comment by mquinson** [comment]
I implemented the file copy without the cp command.

**Comment by mquinson** [comment]
So I'm a bit lost now. What are our options to deduplicate the pages in memory if neither bttr FS nor reflink will help us?

Is punchholing the file the only option we have? 

At the same time, I slowly get the feeling that this optimization is not needed in practice. In the case of HPL, the binary is only 800k, so that will definitely not be the performance killer.

**Comment by Ezibenroc** [comment]
> At the same time, I slowly get the feeling that this optimization is not needed in practice. In the case of HPL, the binary is only 800k, so that will definitely not be the performance killer.

Using `dlopen` for privatization has been a great improvement in HPL.
But if I understood correctly, what you are working on now will only impact the initialization of the program, not the context switches. This initialization is already negligible in HPL, so I don't think it is usefull to look further.

**Comment by mquinson** [comment]
Well, I'm not so sure, @Ezibenroc. What's killing your HPL right now seem to be related to memory usage. Ok, Mostly because the kernel fail to properly prepare the pages that are mmap'ed with the POPULATE flag, but still. I think that dedupplicating the code may help to grow above a given point. The next step seem to be the kernel patch prepared by @sthibaul, but it may well be that the move after this one is the dedupplication. Will see.

**Comment by randomstuff** [comment]
@Ezibenroc, Deduplicating will reduce the memory consumption. Moreover we could expect better performance by reducing CPU cache usage (especially the instruction cache).

**Comment by mquinson** [comment]
I improved the documentation of this feature, explaining what I understand from the work remaining to do. Could you guys please have a look? Thanks.

http://simgrid.gforge.inria.fr/simgrid/3.16/doc/options.html#options_smpi_global

Also, we will need a few test for this. We don't want to dupplicate the whole set of MPI tests, or they will last over one hour. @adegomme, could you please take care of this?

**Comment by sthibaul** [comment]
The idea was, after dlopen()ing several times, to look in /proc/$pid/smaps and remap the original binary file over the file copies mapped by dlopen(), so that we do get code sharing, and only the dynamic linking bits are not shared. I.e. not reimplementing dlopen() to get the wanted behavior, but fix the result of dlopen().

**Comment by mquinson** [comment]
Ok, we now have some tests of this feature, and it works like a charm on mac and freebsd. Simply, it does not like pthreads on these architectures: you gain a SIGBUS somewhere in malloc when you activate both dlopen and pthread at the same time.

But dlopen and raw contextes actually work on Mac and FreeBSD. Privatization is disabled on NetBSD and I did not try to force dlopen on that platform. The week-end was not *that* bad.

Next step will be the interaction with MC, I guess. And the code deduplication.

**Comment by mquinson** [comment]
Closing this PR since there is nothing anymore to merge in it, and the remaining discussion took place in the associated bug #137.

**Pull request closed without merging**
